displayName=Seed Priority
author=IVIystical
description=Prioritises farming destinations when using seeds, saplings, and farming supplies
tags=farming,seed,sapling,birdhouse,patch,leprechaun
version=
plugins=net.wchbdotnet.seedpriority.SeedPriorityPlugin
build=standard
